version: "3.9"

services:
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -lc "pip install -q -r requirements.txt && uvicorn api.app:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  dashboard:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -lc "pip install -q -r requirements.txt && streamlit run dashboards/streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    working_dir: /mlflow
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./mlops/airflow_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 10

  airflow-init:
    image: apache/airflow:2.9.3
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    user: "0:0"
    volumes:
      - ./mlops/airflow_dags:/opt/airflow/dags
      - ./mlops/airflow_logs:/opt/airflow/logs
      - ./mlops/airflow_plugins:/opt/airflow/plugins
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname admin --lastname user --role Admin --email admin@example.com || true"

  airflow-webserver:
    image: apache/airflow:2.9.3
    depends_on:
      - airflow-init
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./mlops/airflow_dags:/opt/airflow/dags
      - ./mlops/airflow_logs:/opt/airflow/logs
      - ./mlops/airflow_plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.3
    depends_on:
      - airflow-init
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./mlops/airflow_dags:/opt/airflow/dags
      - ./mlops/airflow_logs:/opt/airflow/logs
      - ./mlops/airflow_plugins:/opt/airflow/plugins
    command: scheduler
