version: "3.9"

services:
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -lc "pip install -q -r requirements.txt && uvicorn api.app:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  dashboard:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -lc "pip install -q -r requirements.txt && streamlit run dashboards/streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    working_dir: /mlflow
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
